version: '3'
services:
  react-start-nginx:
    container_name: react-start-nginx
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
      args:
        VHOST_FILE: ${VHOST_FILE}
    volumes:
      - ./:/var/www
    ports:
      - 80
    depends_on:
      - react-start-node
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOSTS}
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: ${VIRTUAL_HOSTS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    networks:
      - react-start
      - nginx-proxy

  react-start-node:
    user: ${USER_ID}:${GROUP_ID}
    container_name: react-start-node
    command: /bin/sh ${ENTRYPOINT}
    build:
      context: ./
      dockerfile: docker/node/Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - ./:/var/www
      - ./node_modules:/var/www/node_modules
      - ${NGINX_CERTS_PATH}:/etc/certs
    ports:
      - 60037:60037
    networks:
      - react-start

  react-start-redis:
    container_name: react-start-redis
    build:
      context: ./
      dockerfile: docker/redis/Dockerfile
      args:
        REDIS_PASSWORD: ${REDIS_PASSWORD}
        REDIS_PORT: ${REDIS_PORT}
    ports:
      - ${REDIS_PORT}
    sysctls:
      - net.core.somaxconn=511
    networks:
      - react-start
networks:
  react-start:
  nginx-proxy:
    external: true
